[package]
name = "master_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
proto = { path = "../proto" }
common = { path = "../common" }
priority-queue = "1.3.2"
